version: "3"

services:
  frontend:
    container_name: tile_project_frontend_container
    image: tile_project_frontend_image
    build:
      context: .
    ports:
      - "5000:5000"
    command: npm run dev
